# library(survival)
# library(ROCR)
# library(mvtnorm)
# library(golubEsets)
# library(genefilter)
# library(pheatmap)
# library(class)
# library(foreach)
# library(psych)
# library(DESeq2)
# library(multtest)
# library(splines)
# library(formatR)
# library(lattice)
# library(nlme)
# library(dendextend)
# library(RColorBrewer)
# library(dplyr)

install.packages("survival")
install.packages("ROCR")
install.packages("mvtnorm")
install.packages("class")
install.packages("foreach")
install.packages("psych")
install.packages("splines")
install.packages("formatR")
install.packages("lattice")
install.packages("nlme")
install.packages("dendextend")
install.packages("RColorBrewer")
install.packages("dplyr")
install.packages("pheatmap")

## try http:// if https:// URLs are not supported
source("https://bioconductor.org/biocLite.R")
biocLite()
biocLite("DESeq2")
biocLite("multtest")
biocLite("golubEsets")
biocLite("genefilter")

